export const metadata = {
  title: "Next.js",
  description: "Generated by create Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <link rel="icon" type="image/svg+xml" href="/logo.svg" />
          <meta name="description" content="Popis stránky" />
          <title>HydroLeaf</title>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
